[tool.poetry]
name = "tum"
version = "1.0.1"
description = "TA2 Table Understanding"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sem-desc = "^6.11.3"
serde2 = "^1.6.2"
ream2 = "^4.3.2"
kgdata = "^7.0.0"
drepr-v2 = "^1.3.4"
steiner-tree = "^1.1.3"
dsl2 = "^1.3.2"
rltk = "^2.0.0a20"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.27.1"
black = "^23.11.0"
autoflake = "^2.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
